import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Pricing from "@/components/Pricing-Section";

const geistSans = localFont( {
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
} );
const geistMono = localFont( {
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
} );

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout( {
    children,
}: Readonly<{
    children: React.ReactNode;
}> ) {
    return (
        <html lang="en">
            <body>
                <Pricing />

                {children}
                <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
            </body>
        </html>
    );
}
